### ISSUE TITLE
cfg and toml

### ISSUE THREAD

**Issue by mlindsk** [robertdj/arithmetic1.py#2]
Hi Robert,

I've been told that setup.py is becoming 'the old way' of specifying information in a Python package. The 'new way' is supposedly using pyproject.toml and setup.py as described here:

http://ivory.idyll.org/blog/2021-transition-to-pyproject.toml-example.html

Hope you had a smooth transition to the new job - and merry Christmas  :-)

/M

**Comment by robertdj** [comment]
Hi Mads.

Thanks for pointing that out -- you are absolutely right :-) I started out with `setup.py` to have both approaches in the repo, but it's happening one evening at a time.

Cheers!

**Comment by mlindsk** [comment]
Happy coding :-)
